version: "3.9"
services:
  database:
    container_name: ev_postgres
    image: postgres:latest
    restart: always
    expose:
      - "5432"
    volumes:
      - ./data:/data/db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: eventuredb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

  app:
    container_name: ev_backend
    restart: always
    build: .
    ports:
      - "8082:8081"
    depends_on:
      - database
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://ev_postgres:5432/eventuredb
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
